$axure.loadCurrentPage({
  "url":"主页.html",
  "generationDate":new Date(1438243193203.42),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/主页/bg.png",
    "width":1203,
    "height":800},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"46f6b3a3d06747ca8101531eab74d8f2",
    "type":"Axure:Page",
    "name":"主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e6afb435293d4e6fb1c7c9487272fbad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":166},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4a1048b62554c55b36e36966c431802",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":166},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8863f4198c5444618b73a309d771a9fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":386,
              "y":156},
            "size":{
              "width":554,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEDEDED}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79aaae188ad1476393919a3ee222b455",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":386,
                  "y":156},
                "size":{
                  "width":554,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEDEDED}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u2.png"}},
{
          "id":"f0037177242843099f79de2a8b763f4b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":386,
              "y":156},
            "size":{
              "width":554,
              "height":36}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"case<br> (If 选中项于 This = &quot;创投会议&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"创投会议",
                      "stos":[]}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 formContent to status1",
                      "panelsToStates":[{
                          "panelPath":["fff6d66a3b0f4d56bdaf9663a90b8dba"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"用例 1<br> (Else If 选中项于 This = &quot;户外活动&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"户外活动",
                      "stos":[]}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 formContent to status2",
                      "panelsToStates":[{
                          "panelPath":["fff6d66a3b0f4d56bdaf9663a90b8dba"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"用例 2<br> (Else If 选中项于 This = &quot;线下聚会&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"线下聚会",
                      "stos":[]}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 formContent to status3",
                      "panelsToStates":[{
                          "panelPath":["fff6d66a3b0f4d56bdaf9663a90b8dba"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"用例 3<br> (Else If 选中项于 This = &quot;电影发布&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"电影发布",
                      "stos":[]}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 formContent to status4",
                      "panelsToStates":[{
                          "panelPath":["fff6d66a3b0f4d56bdaf9663a90b8dba"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":4,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"用例 4<br> (Else If 选中项于 This = &quot;沙龙讲座&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"沙龙讲座",
                      "stos":[]}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 formContent to status5",
                      "panelsToStates":[{
                          "panelPath":["fff6d66a3b0f4d56bdaf9663a90b8dba"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":5,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}}},
{
          "id":"fff6d66a3b0f4d56bdaf9663a90b8dba",
          "label":"formContent",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":227},
            "size":{
              "width":60,
              "height":73}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"1e50c19b0376492999cbd6428f775c34",
              "label":"status1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"54cf6db1fef9436d9d3fa1f226bfde89",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"02eacf30566749a48a430603ca19516b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e498dc12b11f4394a2f13ec748e2a76b",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":57},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a78143c529e4a13862c9499a9d078e9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":57},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f0c5d2e763d54c838257f17c96eec782",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":115},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5fe3741bf4c64dea87a39e4da3d09e1f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":115},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8095ef0412b84497a601aff36781a15f",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":192},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"00c0701aa2e846d5b3212439168e9832",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":192},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"aeeae0df6a0e48968e5ff980870a2667",
              "label":"status2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c0dab54d64c34f27bc81826a109d6e43",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"31852e7835f64bb2b53f1af9aca8a0d9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"128c29516179420986d6e3c8c4848330",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":57},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9c71dfa58c1c46eca62f55017b546c4e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":57},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"728c924ea6644d01a3705f8ad8d0d6d4",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":115},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f7e7d8e06d3f4c498c52a4eea5138922",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":115},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9e64910905104a15810f4164f459813e",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":192},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"07225038bdef415d8f7e764dda2aed69",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":192},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"ddb5317997014fc4b0a94104b7916a97",
              "label":"status3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8a9437f1abcd4a2b875fc74684b8bdc6",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a1193a6338b6413a9fb76350a99d466d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4b9e867efa8c4c8d9b8e65073bbed971",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":57},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3c58408f53e54942bc22ac414133e3e1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":57},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8dc4fab8e21143488fd1663ab4b6b507",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":115},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"746a9688d71b4f0c905e82e474054bfc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":115},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"20dcb63a5da14269a091477412b8e4ef",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":192},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d87815eb9bf045d7bcda9eac8508b6b5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":192},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"109be9a07b4949d19476dc9aa7b0947a",
              "label":"status4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d326e627b07b4e2484e8db51bb2de9e5",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b6bf55ea5c10466584f70771515b88ec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a9219dd7eff4402da94e2c4536f83afb",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":57},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"abc60039f1b447c88e16cd55f248cdb5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":57},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f4e9e63244544139b50fbcb698276fd0",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":115},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"28bd0a2e6e5847c1af549988d2e9938c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":115},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"303e668af35c44f3a05d06f2f268b69f",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":192},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"52d0b10158384c299a766296206d0f79",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":192},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"fd97b5285c9a4c4abebfaa163c91d1c1",
              "label":"status5",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"eb388bcba0e54feba696bb9a21619fb5",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d757dfa46ea34f59980b8243ab9728ca",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"39c028755e0a4073927d2bb22f1a8a63",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":57},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"59548137ee4545ae82315105dd27323e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":57},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"dc2f8f7050614a5b917d229bb97855f4",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":115},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c8b5ce67986f4bb59fe086c07d516d2c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":115},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2725e4b2ece9499a915ce8a26148bf0e",
                  "label":"",
                  "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":192},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"08a8449a01a44e9ea5dc57195643c92e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fff6d66a3b0f4d56bdaf9663a90b8dba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":192},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"33f7df7f3f3647f391d35461d11bc403",
              "label":"status6",
              "type":"Axure:PanelDiagram",
              "objects":[]},
{
              "id":"4617f743109f47bd8f9ae2e9a7bd301a",
              "label":"status7",
              "type":"Axure:PanelDiagram",
              "objects":[]}]}]}},
  "masters":{
},
  "objectPaths":{
    "e6afb435293d4e6fb1c7c9487272fbad":{
      "scriptId":"u0"},
    "f4a1048b62554c55b36e36966c431802":{
      "scriptId":"u1"},
    "8863f4198c5444618b73a309d771a9fc":{
      "scriptId":"u2"},
    "79aaae188ad1476393919a3ee222b455":{
      "scriptId":"u3"},
    "f0037177242843099f79de2a8b763f4b":{
      "scriptId":"u4"},
    "fff6d66a3b0f4d56bdaf9663a90b8dba":{
      "scriptId":"u5"},
    "54cf6db1fef9436d9d3fa1f226bfde89":{
      "scriptId":"u6"},
    "02eacf30566749a48a430603ca19516b":{
      "scriptId":"u7"},
    "e498dc12b11f4394a2f13ec748e2a76b":{
      "scriptId":"u8"},
    "4a78143c529e4a13862c9499a9d078e9":{
      "scriptId":"u9"},
    "f0c5d2e763d54c838257f17c96eec782":{
      "scriptId":"u10"},
    "5fe3741bf4c64dea87a39e4da3d09e1f":{
      "scriptId":"u11"},
    "8095ef0412b84497a601aff36781a15f":{
      "scriptId":"u12"},
    "00c0701aa2e846d5b3212439168e9832":{
      "scriptId":"u13"},
    "c0dab54d64c34f27bc81826a109d6e43":{
      "scriptId":"u14"},
    "31852e7835f64bb2b53f1af9aca8a0d9":{
      "scriptId":"u15"},
    "128c29516179420986d6e3c8c4848330":{
      "scriptId":"u16"},
    "9c71dfa58c1c46eca62f55017b546c4e":{
      "scriptId":"u17"},
    "728c924ea6644d01a3705f8ad8d0d6d4":{
      "scriptId":"u18"},
    "f7e7d8e06d3f4c498c52a4eea5138922":{
      "scriptId":"u19"},
    "9e64910905104a15810f4164f459813e":{
      "scriptId":"u20"},
    "07225038bdef415d8f7e764dda2aed69":{
      "scriptId":"u21"},
    "8a9437f1abcd4a2b875fc74684b8bdc6":{
      "scriptId":"u22"},
    "a1193a6338b6413a9fb76350a99d466d":{
      "scriptId":"u23"},
    "4b9e867efa8c4c8d9b8e65073bbed971":{
      "scriptId":"u24"},
    "3c58408f53e54942bc22ac414133e3e1":{
      "scriptId":"u25"},
    "8dc4fab8e21143488fd1663ab4b6b507":{
      "scriptId":"u26"},
    "746a9688d71b4f0c905e82e474054bfc":{
      "scriptId":"u27"},
    "20dcb63a5da14269a091477412b8e4ef":{
      "scriptId":"u28"},
    "d87815eb9bf045d7bcda9eac8508b6b5":{
      "scriptId":"u29"},
    "d326e627b07b4e2484e8db51bb2de9e5":{
      "scriptId":"u30"},
    "b6bf55ea5c10466584f70771515b88ec":{
      "scriptId":"u31"},
    "a9219dd7eff4402da94e2c4536f83afb":{
      "scriptId":"u32"},
    "abc60039f1b447c88e16cd55f248cdb5":{
      "scriptId":"u33"},
    "f4e9e63244544139b50fbcb698276fd0":{
      "scriptId":"u34"},
    "28bd0a2e6e5847c1af549988d2e9938c":{
      "scriptId":"u35"},
    "303e668af35c44f3a05d06f2f268b69f":{
      "scriptId":"u36"},
    "52d0b10158384c299a766296206d0f79":{
      "scriptId":"u37"},
    "eb388bcba0e54feba696bb9a21619fb5":{
      "scriptId":"u38"},
    "d757dfa46ea34f59980b8243ab9728ca":{
      "scriptId":"u39"},
    "39c028755e0a4073927d2bb22f1a8a63":{
      "scriptId":"u40"},
    "59548137ee4545ae82315105dd27323e":{
      "scriptId":"u41"},
    "dc2f8f7050614a5b917d229bb97855f4":{
      "scriptId":"u42"},
    "c8b5ce67986f4bb59fe086c07d516d2c":{
      "scriptId":"u43"},
    "2725e4b2ece9499a915ce8a26148bf0e":{
      "scriptId":"u44"},
    "08a8449a01a44e9ea5dc57195643c92e":{
      "scriptId":"u45"}}});